name: Kimya Gandhi Invites
favicon: null
layout_spectrum: 0.88129
typography_spectrum: 0.95936
title: Custom Wedding Invitations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
